// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220722094307_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entity.Entites.Game", b =>
                {
                    b.Property<int>("gameid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gameid"), 1L, 1);

                    b.Property<string>("gamename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("gameid");

                    b.ToTable("Oyunlar");
                });

            modelBuilder.Entity("Entity.Entites.info", b =>
                {
                    b.Property<int>("gameinfoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gameinfoid"), 1L, 1);

                    b.Property<int>("Oyunlargameid")
                        .HasColumnType("int");

                    b.Property<string>("gamecategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("gameinfoid");

                    b.HasIndex("Oyunlargameid");

                    b.ToTable("Bilgiler");
                });

            modelBuilder.Entity("Entity.Entites.info", b =>
                {
                    b.HasOne("Entity.Entites.Game", "Oyunlar")
                        .WithMany("Bilgiler")
                        .HasForeignKey("Oyunlargameid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oyunlar");
                });

            modelBuilder.Entity("Entity.Entites.Game", b =>
                {
                    b.Navigation("Bilgiler");
                });
#pragma warning restore 612, 618
        }
    }
}
